name: Install Package

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            
            - name: LS
              run: |
                chmod +x installPackage.sh
                ./installPackage.sh